Added methods to Enums
spdx/schema-to-java pull request #9
Opened 2020-08-22 14:34 UTC by AnishaSrivastava1411

Adding methods in enums.

2020-08-24 15:29 UTC, rtgdk requested changes

2020-08-24 15:29 UTC, rtgdk commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +            Emethod.modifiers().add(modifier);
A lot of indentation mismatch in the file, I am not sure how eclipse is not handling this well. Also, in every PR, there are some or the other whitespace in a lot of files, not sure how these are being created either.

2020-08-25 17:41 UTC, AnishaSrivastava1411 commented
I have added the SPDXNameConverter.java. Here is the link:  https://github.com/AnishaSrivastava1411/schema-to-java/blob/master/side-project/Decorator/SPDXNameConverter.java

I used this class to modify enum value in SPDXClassDecorator.java. Please refer the link:
https://github.com/AnishaSrivastava1411/schema-to-java/blob/0ca6d2c4129fa70549b037d9f831c518a6950074/side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java#L218

But I'm not able to get the "enum value".
Please guide. @goneall

2020-08-25 17:47 UTC, AnishaSrivastava1411 commented
I can add few more if-else conditions in SPDXNameConverter.java to modify the enumeration values.

2020-08-25 21:56 UTC, goneall commented
> But I'm not able to get the "enum value".

Rather than calling the nameconverter from the SPDXClassDecorator, configure it to be called for every value on the XSD global configuration file

```
<name-converter class=org.spdx.jibx.SPDXNameConverter"/>
```

This will then be called for every declaration.  See http://jibx.sourceforge.net/fromschema/codegen-extends.html for configuration details.

In the SPDXNameConverter implementation, you can check for the Enumeration constant name and convert it if at matches.  If it doesn't match, you need to return `super.toConstantName(text)`.

I searched most of the day and could not find a way to determine if the toConstantName is getting called for an Enumeration or for some other constant, so we'll have to do something less than ideal.

There are a limited number of enumeration classes, they are all found at https://github.com/spdx/Spdx-Java-Library/tree/master/src/main/java/org/spdx/library/model/enumerations

You can match by searching for the prefix of the values (e.g. 

```
if (text.startsWith("annotationType_")) {
   return text.substring("annotationType_".lenght); 
} else if (text.startsWith("checksumAlgorithm_")) {
   return text.substring("checksumAlgorithm_".lenght); 
}  else if 
...
} else {
   return super.toConstantName(text);
}
```

for all the enum classes

2020-08-26 15:09 UTC, AnishaSrivastava1411 commented
The new changes in enums are not as expected. Please have a look.
https://github.com/AnishaSrivastava1411/schema-to-java/blob/63218f0b1b44c3957f73248edc42bbbf7601afad/src/main/source-code/org/spdx/library/model/RelationshipType.java#L10.
This is happening  with every enum value.

Also, when I'm used ```return text.substring("FILE_TYPE_".length()); ``` after each if-condition and ``` return super.toConstantName(text);``` at the end of the method as the return statement, the changes in decorator class were not getting reflected in enums. 
But when I just used ```return text;``` it made changes.

2020-08-26 16:03 UTC, goneall commented
It looks like it is always returning "text".

A couple of comments:

- If it doesn't match, you should call the superclass toConstantName class.  Returning just the text will cause it not to translate any of the constants.  If calling that method doesn't work, you'll need to debug why.  
- I haven't actually tested the code I submitted, so it may have some small defects - I would run the debugger and set a breakpoint to find out what's happening (or print out the values to the console)
- Based on the results, it looks like it is always returning text without any changes, so it is not satisfying the `if` conditionals.

I think it is getting passed the lowercase values, so the `if` statements may need to be modified to check for the lowercase values (e.g. `relationshipType_`).

2020-08-26 18:12 UTC, AnishaSrivastava1411 commented
Now it returns enum values in the lower case following camel-case instead to Upper Case and snake-case. Will this work?
@goneall

2020-08-26 23:31 UTC, goneall commented
@AnishaSrivastava1411 You can shift it to uppercase then it will match the model code.

2020-08-26 23:33 UTC, goneall commented
@AnishaSrivastava1411 Actually, if you call superclass method with the substring, it will do the camelCase conversion for you.

2020-08-27 07:48 UTC, AnishaSrivastava1411 commented
I am using tabs for indentation of indent-size = 4 but it's getting messed up after committing while the codes look fine locally after git push.
May you please help in resolving this?

2020-08-27 10:34 UTC, AnishaSrivastava1411 commented
> I am using tabs for indentation of indent-size = 4 but it's getting messed up after committing while the codes look fine locally after git push.
> May you please help in resolving this?

Resolved in last commit.

2020-08-27 15:49 UTC, AnishaSrivastava1411 commented
Please review. @goneall @rtgdk

2020-08-27 16:09 UTC, goneall commented on side-project/Decorator/SPDXNameConverter.java
> +        if(text.startsWith("referenceCategory_"))
Indentation looks off here

2020-08-27 16:13 UTC, goneall commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +	}
What are these properties and set methods used for?  If they are unused, they should be removed.

2020-08-27 16:15 UTC, goneall commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +	}
I see these being used later in the finish method, but I don't quite understand how the code works or the purpose.  Perhaps some comments in the finish method would help.

2020-08-27 16:18 UTC, goneall commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +		if(!(holder instanceof EnumerationClassHolder)) {
Code cleanup request - the start method is now very long making it hard to read.  Suggest refactoring the code inside this if statement into a separate method calls that have a meaningful name (e.g. `createConstructors(holder, ast);`

2020-08-27 16:20 UTC, goneall commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +			Modifier modifier = ast.newModifier(Modifier.ModifierKeyword.PUBLIC_KEYWORD);
This code inside this if statement can be moved to a separate method.  It can also be moved inside the same if statement above since they are both `if (!(holder instanceof EnumerationClassHolder))`

2020-08-27 16:21 UTC, goneall commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +		if(holder instanceof EnumerationClassHolder){
This could be an `else` to the above conditional rather than a separate if statement

2020-08-27 16:21 UTC, goneall commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +			SimpleName fieldname = ast.newSimpleName("longName");
Another opportunity to separate this out into a separate method for better readability.

2020-08-27 16:23 UTC, goneall commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +			MethodInvocation mi = ast.newMethodInvocation();
Instead of using generic variable names like `mi`, `mi2`, `modifier`, etc. it is much more readable and supportable to use variable names with meaning such as `miGetLongName`.

2020-08-27 16:28 UTC, goneall commented on src/main/source-code/org/spdx/library/model/ChecksumAlgorithm.java
> +        return "longName";
It looks like the jibx is generating code to set the property `value` rather than `longName`.  The easiest fix would be to remove the `private String longName` and change the above to return `value` rather than `longName`.

2020-08-28 10:05 UTC, rtgdk requested changes
Left some major comments for refactoring the code

2020-08-28 10:05 UTC, rtgdk commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +
You should try to keep whitespace diff minimal, use 2/4 spaces instead of tab for indentation

2020-08-28 10:05 UTC, rtgdk commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +			param5.setName(ast.newSimpleName(param_nameCreate));
Use better variable naming `paramNameModelStore` instead of `param1` and `nameModelStore` instead of `param_nameModelStore`

2020-08-28 10:05 UTC, rtgdk commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +			param5.setName(ast.newSimpleName(param_nameCreate));
Similarly for other variables too - constr, sname, param_type, constructorName, etc.

2020-08-28 10:05 UTC, rtgdk commented on side-project/Decorator/org/spdx/jibx/SPDXClassDecorator.java
> +			holder.addMethod(methodGetType);
Separate these blocks of statements into  different functions, will make the code easier to read, and you can reuse the functions elsewhere

2020-08-29 16:22 UTC, merged